// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srogquicuqyzbbplavpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyb2dxdWljdXF5emJicGxhdnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzY3NTQsImV4cCI6MjA2NTg1Mjc1NH0.YaPHljZvP_IXKlM2uuLlUkHjBOaIciDQMJC-TKZW_wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);